id: P002894
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:26:53.162208
source_metadata:
  id: bdr:W23204
  title: ཉེས་ལྟུང་བཤགས་སྐོར
  author: ''
  volumes:
    376a95206d1d420b92145942f8c2cf85:
      image_group_id: I0840
      title: ''
      volume_number: 1
      total_pages: 38
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
