id: I998312B4
legacy_id: P002894
ocr_import_info:
  bdrc_scan_id: W23204
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T14:36:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T00:59:57.130686+00:00'
last_modified: 2022-09-02 09:00:01.810363
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23204
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23204
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཉེས་ལྟུང་བཤགས་སྐོར།
  author: ཀརྨ་མཁན་ཆེན་ཀརྨ་རཏྣ།
statistics:
  ocr_word_mean_confidence_index: 0.8690447538163458
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I0840:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0840
      total_pages: 38
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0840.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8690447538163458
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
